language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greet_app_database

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  greet_app_database;' -U postgres
  - psql -U postgres -d greet_app_database -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2